const bibleCodes='GEN EXO LEV NUM DEU JOS JDG RUT 1SA 2SA 1KI 2KI 1CH 2CH EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZK DAN HOS JOL AMO OBA JON MIC NAM HAB ZEP HAG ZEC MAL MAT MRK LUK JHN ACT ROM 1CO 2CO GAL EPH PHP COL 1TH 2TH 1TI 2TI TIT PHM HEB JAS 1PE 2PE 1JN 2JN 3JN JUD REV'.split(' ');
export const books=[
['Genesis','उत्पत्ति',50,'ot'],['Exodus','प्रस्थान',40,'ot'],['Leviticus','लेवी',27,'ot'],['Numbers','गन्ती',36,'ot'],['Deuteronomy','व्यवस्था',34,'ot'],['Joshua','यहोशू',24,'ot'],['Judges','न्यायकर्ताहरू',21,'ot'],['Ruth','रूथ',4,'ot'],['1 Samuel','१ शमूएल',31,'ot'],['2 Samuel','२ शमूएल',24,'ot'],['1 Kings','१ राजा',22,'ot'],['2 Kings','२ राजा',25,'ot'],['1 Chronicles','१ इतिहास',29,'ot'],['2 Chronicles','२ इतिहास',36,'ot'],['Ezra','एज्रा',10,'ot'],['Nehemiah','नहेम्याह',13,'ot'],['Esther','एस्तर',10,'ot'],['Job','अय्यूब',42,'ot'],['Psalms','भजनसंग्रह',150,'ot'],['Proverbs','हितोपदेश',31,'ot'],['Ecclesiastes','उपदेशक',12,'ot'],['Song of Solomon','श्रेष्ठगीत',8,'ot'],['Isaiah','यशैया',66,'ot'],['Jeremiah','यर्मिया',52,'ot'],['Lamentations','विलाप',5,'ot'],['Ezekiel','इजकिएल',48,'ot'],['Daniel','दानिएल',12,'ot'],['Hosea','होशे',14,'ot'],['Joel','योएल',3,'ot'],['Amos','आमोस',9,'ot'],['Obadiah','ओबदिया',1,'ot'],['Jonah','योना',4,'ot'],['Micah','मीका',7,'ot'],['Nahum','नहूम',3,'ot'],['Habakkuk','हबकूक',3,'ot'],['Zephaniah','सपन्याह',3,'ot'],['Haggai','हाग्गै',2,'ot'],['Zechariah','जकरिया',14,'ot'],['Malachi','मलाकी',4,'ot'],['Matthew','मत्ती',28,'nt'],['Mark','मर्कूस',16,'nt'],['Luke','लूका',24,'nt'],['John','यूहन्ना',21,'nt'],['Acts','प्रेरित',28,'nt'],['Romans','रोमी',16,'nt'],['1 Corinthians','१ कोरिन्थी',16,'nt'],['2 Corinthians','२ कोरिन्थी',13,'nt'],['Galatians','गलाती',6,'nt'],['Ephesians','एफिसी',6,'nt'],['Philippians','फिलिप्पी',4,'nt'],['Colossians','कलस्सी',4,'nt'],['1 Thessalonians','१ थेसलोनिकी',5,'nt'],['2 Thessalonians','२ थेसलोनिकी',3,'nt'],['1 Timothy','१ तिमोथी',6,'nt'],['2 Timothy','२ तिमोथी',4,'nt'],['Titus','तीतस',3,'nt'],['Philemon','फिलेमोन',1,'nt'],['Hebrews','हिब्रू',13,'nt'],['James','याकूब',5,'nt'],['1 Peter','१ पत्रुस',5,'nt'],['2 Peter','२ पत्रुस',3,'nt'],['1 John','१ यूहन्ना',5,'nt'],['2 John','२ यूहन्ना',1,'nt'],['3 John','३ यूहन्ना',1,'nt'],['Jude','यहूदा',1,'nt'],['Revelation','प्रकाश',22,'nt']
].map(([en,ne,chapters,testament],i)=>({en,ne,chapters,testament,code:bibleCodes[i]}));

export const featured=[
{ref:'भजनसंग्रह २३:१',text:'परमप्रभु मेरा गोठाला हुनुहुन्छ, मलाई केही कुराको अभाव हुँदैन।'},
{ref:'यूहन्ना ३:१६',text:'किनभने परमेश्वरले संसारलाई यस्तो प्रेम गर्नुभयो कि उहाँले आफ्नो एकमात्र पुत्र दिनुभयो।'},
{ref:'फिलिप्पी ४:१३',text:'जसले मलाई शक्ति दिनुहुन्छ, उहाँमा म सबै कुरा गर्न सक्छु।'}
];
